


stages:
- stage: rdpToCentOS
  displayName: 'rdpToCentOS'
  jobs:
  - deployment: 'rdpToCentOS'
    displayName: 'rdpToCentOS'
    environment:
     name: myLinuxVM
     resourceType: VirtualMachine
     tags: centos
    strategy:
     runOnce:
      deploy:
       steps:
       - script: 
         

- stage: rdpToUbuntu
  displayName: rdpToUbuntu
  jobs:
  - deployment: 'rdpToUbuntu'
    displayName: 'rdpToUbuntu'
    environment:
      name: myLinuxVM
      resourceType: VirtualMachine
      tags: ubuntu
    strategy:
     runOnce:
      deploy:
        steps:
        - script: 